# ASSIGNMENT
import cmath
# WRITE A SIMPLE PROGRAM THAT CAN SOLVE QUADRATIC EQUATION USING ALMIGHT FORMULAR

# "ax ** 2 + bx + c" 
# let define our a + b +c below

# a = 5
# b = 6
# c = 1
# #let introduce ALMIGHT FORMULAR
# x= (b**2) - (4*a*c)

# equ1 = (-b-cmath.sqrt(x))/ (2*a)
# equ2 = (-b+cmath.sqrt(x))/ (2*a)
# print ("{0},{1}".format(equ1,equ2))

# a = float (input("enter value of a "))
# b = float (input("enter value of b "))
# c = float (input("enter value of c "))
# # let introduce Almight formular 
# x= (b**2) - (4*a*c)

# equ1 = (-b-cmath.sqrt(x))/ (2*a)
# equ2 = (-b+cmath.sqrt(x))/ (2*a)
# print("{0},{1}".format(equ1,equ2))
 
# pythagora forumlar
 
# import square function from math
# a2 + b2 = c2 
# a = 3
# b = 4
# c = 0
# number = "3 ** 0.5 + 4 ** 0.5 = c ** 0.5"
# print (number)

# a = float (input("enter value of a"))
# b = float (input("enter value of b"))
# c = float (input("enter value of c"))
# x= (b**2) - (4*a*c)

# equ1 = (-b- (x**0.5))/ (2*a)
# equ2 = (-b+ (x**0.5))/ (2*a)
# print ("{0},{1}".format(equ1,equ2))

# a = int (input("enter the value of  a ? "))
# b = int ( input("enter the value of b ?"))
# z = (a ** 2) + (b ** 2 )
# to_get_our_c = z ** 0.5
# print (to_get_our_c)
# price of a house is #1000000 if buyer has good credit, they need to put down 10% otherwise they need to put down 20% 

# price = 1000000
# has_good_credit_score = True

# if has_good_credit_score: 
#     down_payment= price * 0.1
# else:
#     down_payment= price * 0.2
# print (f"down_payment:# {down_payment}")

# price of a car is 500000 if buyer has good credit and has no criminal record they need to put down 30% otherwise they will put down 50%

# price_of_a_car = 500000
# has_good_credit = False
# has_no_criminal_record = True


# if has_good_credit:
#     down_payment = price_of_a_car * 0.3
# elif has_no_criminal_record:
#     down_payment = price_of_a_car * 0.5
# print (f"down_payment:#{down_payment}")

# if an applicant has high income and/or good credit 
#  print (eligible for loan )

# has_high_icome = False
# good_credit = False

# if has_high_icome or good_credit:
#     print ("eligible for loan")
# from time import sleep

# print (10)
# sleep (5)
# print ("*" * 10 )
# sleep (4)

# if name is less than 3 charaters long name must be at least 3 charaters
# otherwise if it more than 50 charaters long name can ba a maximum of 50 characters 
# otherwise name looks good.

# name = "john smith"

# if len (name) < 3:
#     print ("name must be at least 3 charaters")
# elif len (name) > 50:
#     print ("name can be a maximum of 50 charaters")
# else:
#     print ("name looks good")
# x = 2000
# x *= 10
# # print(x)
# x = (1000,2000,1000,80)
# xyz = sum(x)
# print(xyz)
# price = 1000000
# has_good_credit =False
# has_criminal_record = False


# if has_criminal_record or has_good_credit:
#     print("Eligible for loan")
# else:
#     print ("not Eligible for loan")
# price = 100000
# has_good_credit = False


# if has_good_credit:
#     down_payment = 0.1 * price
# else:
#     down_payment = 0.2 * price
# print(f"down_payment:{down_payment}")
